AllCops:
  Exclude:
    - vendor/**
    - tmp/**
    - cookbooks/**
    - bin/**

# allow for alignment of indentations
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Let's not argue over this...
StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

# This isn't javascript, gotta be super careful with the Ruby parser.
DotPosition:
  Enabled: false

# Whitespace between modules/classes/methods can be helpful to read and
# don't hurt anybody.
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# When this is useful, it's useful, every other time it's entirely surprising
# to new Rubyists, let's make it higher at least
NumericLiterals:
  MinDigits: 12

# ABC complexity is a far better code smell signal than raw method length.
MethodLength:
  Max: 50

LineLength:
  Enabled: false
###

# This can make what we're working with in a given method pop more, especially for new rubyists
EmptyLiteral:
  Enabled: false

# Other tooling can detect and handle this, too many false positives.
Documentation:
  Enabled: false

# For chef cookbooks this results in false positives
ParenthesesAsGroupedExpression:
  Enabled: false

# This isn't practical for all the spec code
BracesAroundHashParameters:
  Enabled: false

# Emacs ruby-mode handles this just fine thanks
IndentHash:
  Enabled: false

IndentArray:
  Enabled: false

SignalException:
  Enabled: false

# Pretty sure this isn't a requirement anywhere else
PercentLiteralDelimiters:
  Enabled: false

AlignParameters:
  Enabled: false

# Temporary during refactor for federated.rb recipe
# Offence count: 1
BlockNesting:
  Max: 5

Encoding:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
